### Authentication API

### Ping the server
GET http://localhost:4000/ping

### Register a new user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "company": "MeetPay",
  "name": "Arseniy",
  "email": "mironovq0@gmail.com",
  "phone": "+123456337890",
  "password": "Qwerty12e"
}


### Login with existing user
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "mironovq30@gmail.com",
  "password": "Qwerty12e"
}

> {% client.global.set("auth_token", response.body.data.token); %}

### Access protected route
GET http://localhost:4000/auth/chek
Authorization: Bearer {{auth_token}}

### Change password
POST http://localhost:4000/auth/change-password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "oldPassword": "Qwerty12e",
  "newPassword": "NewPassword123"
}

### Request password reset
# Sends a request to reset the password for a given email
# If the email exists, a reset code will be sent (in a real app)
POST http://localhost:4000/auth/request-password-reset
Content-Type: application/json

{
  "email": "mironovq30@gmail.com"
}

### Verify password reset and set new password
# Verifies the reset code and sets a new password
# The code should be the one received after requesting a password reset
POST http://localhost:4000/auth/verify-password-reset
Content-Type: application/json

{
  "email": "mironovq30@gmail.com",
  "code": "886306",
  "newPassword": "NewSecurePassword123"
}
