### QR Codes

###
GET http://localhost:4000/qrcodes/restaurant/8

###
GET http://localhost:4000/qrcodes/restaurant/8/download

###
GET http://localhost:4000/qrcodes/restaurant/8/table/10

###
GET http://localhost:4000/qrcodes/restaurant/8/table/10/download

